//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.Jx_fapiao {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtcgdbhao;
		protected global::System.Web.UI.WebControls.TextBox txtkaipr;
		protected global::System.Web.UI.WebControls.TextBox txtfpneixing;
		protected global::System.Web.UI.WebControls.TextBox txtjbanr;
		protected global::System.Web.UI.WebControls.TextBox txtcal;
		protected global::System.Web.UI.WebControls.TextBox txtfphao;
		protected global::System.Web.UI.WebControls.TextBox txtriqi;
		protected global::System.Web.UI.WebControls.TextBox txtkpdanw;
		protected global::System.Web.UI.WebControls.TextBox txtkpdunwei;
		protected global::System.Web.UI.WebControls.TextBox txtkpjine;
		protected global::System.Web.UI.WebControls.TextBox txtshuinv;
		protected global::System.Web.UI.WebControls.TextBox txtshuie;
		protected global::System.Web.UI.WebControls.TextBox txtbz;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
