//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.parts {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPN;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtjobnum;
		protected global::System.Web.UI.WebControls.TextBox txtARef;
		protected global::System.Web.UI.WebControls.TextBox txtsize;
		protected global::System.Web.UI.WebControls.TextBox txtsm;
		protected global::System.Web.UI.WebControls.TextBox txtBarcode;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
