//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.fuk_dan {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtfkfs;
		protected global::System.Web.UI.WebControls.TextBox txtfkjine;
		protected global::System.Web.UI.WebControls.TextBox txtdxjine;
		protected global::System.Web.UI.WebControls.TextBox txtbz;
		protected global::System.Web.UI.WebControls.TextBox txtskdw;
		protected global::System.Web.UI.WebControls.TextBox txtjsr;
		protected global::System.Web.UI.WebControls.TextBox txtdjbh;
		protected global::System.Web.UI.WebControls.TextBox txtshijian;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
