//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.cg {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtXUHAO;
		protected global::System.Web.UI.WebControls.TextBox txtRIQI;
		protected global::System.Web.UI.WebControls.TextBox txtMINGCHEN;
		protected global::System.Web.UI.WebControls.TextBox txtCHESHU;
		protected global::System.Web.UI.WebControls.TextBox txtDUNWEI;
		protected global::System.Web.UI.WebControls.TextBox txtDANJIA;
		protected global::System.Web.UI.WebControls.TextBox txtJINE;
		protected global::System.Web.UI.WebControls.TextBox txtBEIZHU;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
