//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.cg {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblXUHAO;
	protected global::System.Web.UI.WebControls.Label lblRIQI;
	protected global::System.Web.UI.WebControls.Label lblMINGCHEN;
	protected global::System.Web.UI.WebControls.Label lblCHESHU;
	protected global::System.Web.UI.WebControls.Label lblDUNWEI;
	protected global::System.Web.UI.WebControls.Label lblDANJIA;
	protected global::System.Web.UI.WebControls.Label lblJINE;
	protected global::System.Web.UI.WebControls.Label lblBEIZHU;


       
    }
}
