//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.nep {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcpmc;
		protected global::System.Web.UI.WebControls.TextBox txtcs;
		protected global::System.Web.UI.WebControls.TextBox txtssdw;
		protected global::System.Web.UI.WebControls.TextBox txtkfdw;
		protected global::System.Web.UI.WebControls.TextBox txtdc;
		protected global::System.Web.UI.WebControls.TextBox txtdj;
		protected global::System.Web.UI.WebControls.TextBox txtje;
		protected global::System.Web.UI.WebControls.TextBox txtbz;
		protected global::System.Web.UI.WebControls.TextBox txtgydw;
		protected global::System.Web.UI.WebControls.TextBox txtjsr;
		protected global::System.Web.UI.WebControls.TextBox txtsj;
		protected global::System.Web.UI.WebControls.TextBox txtddbh;
		protected global::System.Web.UI.WebControls.TextBox txtdjbh;
		protected global::System.Web.UI.WebControls.TextBox txtskfs;
		protected global::System.Web.UI.WebControls.TextBox txtfkjine;
		protected global::System.Web.UI.WebControls.TextBox txtyue;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
