//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.nep {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcpmc;
	protected global::System.Web.UI.WebControls.Label lblcs;
	protected global::System.Web.UI.WebControls.Label lblssdw;
	protected global::System.Web.UI.WebControls.Label lblkfdw;
	protected global::System.Web.UI.WebControls.Label lbldc;
	protected global::System.Web.UI.WebControls.Label lbldj;
	protected global::System.Web.UI.WebControls.Label lblje;
	protected global::System.Web.UI.WebControls.Label lblbz;
	protected global::System.Web.UI.WebControls.Label lblgydw;
	protected global::System.Web.UI.WebControls.Label lbljsr;
	protected global::System.Web.UI.WebControls.Label lblsj;
	protected global::System.Web.UI.WebControls.Label lblddbh;
	protected global::System.Web.UI.WebControls.Label lbldjbh;
	protected global::System.Web.UI.WebControls.Label lblskfs;
	protected global::System.Web.UI.WebControls.Label lblfkjine;
	protected global::System.Web.UI.WebControls.Label lblyue;


       
    }
}
