//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.xx_fapiao {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblxsdbhao;
	protected global::System.Web.UI.WebControls.Label lblkpren;
	protected global::System.Web.UI.WebControls.Label lblfpnxing;
	protected global::System.Web.UI.WebControls.Label lbljbanr;
	protected global::System.Web.UI.WebControls.Label lbllxr;
	protected global::System.Web.UI.WebControls.Label lblfph;
	protected global::System.Web.UI.WebControls.Label lblriqi;
	protected global::System.Web.UI.WebControls.Label lblkpdanw;
	protected global::System.Web.UI.WebControls.Label lblkpdunwei;
	protected global::System.Web.UI.WebControls.Label lblkpjine;
	protected global::System.Web.UI.WebControls.Label lblshuinv;
	protected global::System.Web.UI.WebControls.Label lblshuie;
	protected global::System.Web.UI.WebControls.Label lblbz;


       
    }
}
