//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.xsddan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblxh;
	protected global::System.Web.UI.WebControls.Label lblrq;
	protected global::System.Web.UI.WebControls.Label lblcpmc;
	protected global::System.Web.UI.WebControls.Label lblcs;
	protected global::System.Web.UI.WebControls.Label lbldwei;
	protected global::System.Web.UI.WebControls.Label lbldj;
	protected global::System.Web.UI.WebControls.Label lbljine;
	protected global::System.Web.UI.WebControls.Label lbldanwei;
	protected global::System.Web.UI.WebControls.Label lbljsr;
	protected global::System.Web.UI.WebControls.Label lblddbh;
	protected global::System.Web.UI.WebControls.Label lbldjbh;
	protected global::System.Web.UI.WebControls.Label lblbz;


       
    }
}
