//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.NEP_table {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtcheshu;
		protected global::System.Web.UI.WebControls.TextBox txtdunwei;
		protected global::System.Web.UI.WebControls.TextBox txtdanjia;
		protected global::System.Web.UI.WebControls.TextBox txtjine;
		protected global::System.Web.UI.WebControls.TextBox txtRemarks;
		protected global::System.Web.UI.WebControls.TextBox txtgonyingdanwei;
		protected global::System.Web.UI.WebControls.TextBox txtjinshouren;
		protected global::System.Web.UI.WebControls.TextBox txtdingdanbianhao;
		protected global::System.Web.UI.WebControls.TextBox txtdanjubianhao;
		protected global::System.Web.UI.WebControls.TextBox txtlurushijian;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
