//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.NEP_table {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblcheshu;
	protected global::System.Web.UI.WebControls.Label lbldunwei;
	protected global::System.Web.UI.WebControls.Label lbldanjia;
	protected global::System.Web.UI.WebControls.Label lbljine;
	protected global::System.Web.UI.WebControls.Label lblRemarks;
	protected global::System.Web.UI.WebControls.Label lblgonyingdanwei;
	protected global::System.Web.UI.WebControls.Label lbljinshouren;
	protected global::System.Web.UI.WebControls.Label lbldingdanbianhao;
	protected global::System.Web.UI.WebControls.Label lbldanjubianhao;
	protected global::System.Web.UI.WebControls.Label lbllurushijian;


       
    }
}
