//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.test {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtmeasureb;
		protected global::System.Web.UI.WebControls.TextBox txttime;
		protected global::System.Web.UI.WebControls.TextBox txtstep1;
		protected global::System.Web.UI.WebControls.TextBox txtstep2;
		protected global::System.Web.UI.WebControls.TextBox txtstep3;
		protected global::System.Web.UI.WebControls.TextBox txtstep4;
		protected global::System.Web.UI.WebControls.TextBox txtstep5;
		protected global::System.Web.UI.WebControls.TextBox txtOKorNG;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
