//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cccc.skdan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblskfs;
	protected global::System.Web.UI.WebControls.Label lblskjine;
	protected global::System.Web.UI.WebControls.Label lbldxjine;
	protected global::System.Web.UI.WebControls.Label lblbeizhu;
	protected global::System.Web.UI.WebControls.Label lblfkdw;
	protected global::System.Web.UI.WebControls.Label lbljsr;
	protected global::System.Web.UI.WebControls.Label lbldjbh;
	protected global::System.Web.UI.WebControls.Label lblshijian;


       
    }
}
